language: java
jdk: oraclejdk8


install: true
script: 
  - ./mvnw clean install

cache:
  directories:
  - $HOME/.m2
<<<<<<< HEAD

  vasanth
=======
  Dheeraj
  
>>>>>>> 0a842b5d88e40dff006b909afb4611a7dc5f0e77
